import React, { useRef, useEffect } from 'react';
import { useForm } from '@inertiajs/react';
import { X, Sparkles, Volume2, Save } from 'lucide-react';
import PinyinHelper from './PinyinHelper';
import { pinyinToIndonesianReading, convertToneNumbersToAccents } from '@/utils/pinyinPhonetic';
import { Vocab } from '@/types';

interface VocabFormModalProps {
    isOpen: boolean;
    onClose: () => void;
    vocab?: Vocab | null;
}

interface VocabFormData {
    hanzi: string;
    pinyin: string;
    dibaca: string;
    meaning: string;
    notes: string;
}

export default function VocabFormModal({ isOpen, onClose, vocab = null }: VocabFormModalProps) {
    const isEdit = Boolean(vocab && vocab.id !== 0);
    const pinyinInputRef = useRef<HTMLInputElement>(null);

    const { data, setData, post, put, processing, errors, reset, clearErrors } = useForm<VocabFormData>({
        hanzi: '',
        pinyin: '',
        dibaca: '',
        meaning: '',
        notes: '',
    });

    useEffect(() => {
        if (vocab) {
            setData({
                hanzi: vocab.hanzi || '',
                pinyin: vocab.pinyin || '',
                dibaca: vocab.dibaca || '',
                meaning: vocab.meaning || '',
                notes: vocab.notes || '',
            });
        } else {
            reset();
        }
        clearErrors();
    }, [vocab, isOpen]);

    if (!isOpen) return null;

    const handlePinyinChange = (rawPinyin: string) => {
        const newPinyin = convertToneNumbersToAccents(rawPinyin);
        setData((prev) => {
            const autoReading = pinyinToIndonesianReading(newPinyin);
            const prevAuto = pinyinToIndonesianReading(prev.pinyin);
            const shouldAutoUpdate = !prev.dibaca || prev.dibaca === prevAuto;

            return {
                ...prev,
                pinyin: newPinyin,
                dibaca: shouldAutoUpdate ? autoReading : prev.dibaca,
            };
        });
    };

    const handleAutoGenerateDibaca = () => {
        if (!data.pinyin) return;
        const auto = pinyinToIndonesianReading(data.pinyin);
        setData('dibaca', auto);
    };

    const handleInsertPinyinTone = (char: string) => {
        const input = pinyinInputRef.current;
        let newVal = data.pinyin + char;
        if (input) {
            const start = input.selectionStart ?? data.pinyin.length;
            const end = input.selectionEnd ?? data.pinyin.length;
            const currentVal = data.pinyin;
            newVal = currentVal.substring(0, start) + char + currentVal.substring(end);

            setTimeout(() => {
                input.focus();
                input.setSelectionRange(start + char.length, start + char.length);
            }, 10);
        }

        handlePinyinChange(newVal);
    };

    const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
        // IME-safe check: prevent premature submit when typing Chinese with IME
        if (e.key === 'Enter' && (e.nativeEvent.isComposing || e.keyCode === 229)) {
            return;
        }
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        if (isEdit && vocab) {
            put(route('vocabs.update', vocab.id), {
                onSuccess: () => {
                    reset();
                    onClose();
                },
            });
        } else {
            post(route('vocabs.store'), {
                onSuccess: () => {
                    reset();
                    onClose();
                },
            });
        }
    };

    const playPreviewAudio = () => {
        if (!data.hanzi) return;
        if ('speechSynthesis' in window) {
            window.speechSynthesis.cancel();
            const utterance = new SpeechSynthesisUtterance(data.hanzi);
            utterance.lang = 'zh-CN';
            utterance.rate = 0.85;
            window.speechSynthesis.speak(utterance);
        }
    };

    return (
        <div className="fixed inset-0 z-50 overflow-y-auto bg-black/75 backdrop-blur-md flex items-center justify-center p-4 sm:p-6 animate-fadeIn">
            <div
                className="relative w-full max-w-2xl bg-white dark:bg-slate-900 border border-slate-300/80 dark:border-slate-700/80 rounded-3xl shadow-2xl shadow-rose-950/20 overflow-hidden flex flex-col"
                onClick={(e) => e.stopPropagation()}
            >
                {/* Modal Header */}
                <div className="flex items-center justify-between px-6 py-5 border-b border-slate-200 dark:border-slate-800 bg-slate-900/80">
                    <div className="flex items-center gap-2.5">
                        <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-rose-600 to-amber-500 flex items-center justify-center text-white shadow-lg shadow-rose-600/30">
                            <Sparkles className="w-5 h-5" />
                        </div>
                        <div>
                            <h2 className="text-lg font-bold text-white">
                                {isEdit ? 'Edit Kosakata' : 'Tambah Kosakata Mandarin'}
                            </h2>
                            <p className="text-xs text-slate-400">
                                {isEdit ? 'Perbarui informasi kata Mandarin' : 'Simpan kata baru dengan Hanzi, Pinyin, dan artinya'}
                            </p>
                        </div>
                    </div>
                    <button
                        type="button"
                        onClick={onClose}
                        className="p-2 rounded-xl text-slate-400 dark:text-slate-500 dark:text-slate-400 hover:text-white hover:bg-slate-100 dark:bg-slate-800 transition-colors"
                    >
                        <X className="w-5 h-5" />
                    </button>
                </div>

                <form onSubmit={handleSubmit} className="p-6 space-y-5">
                    {/* Live Preview Card */}
                    <div className="bg-gradient-to-br from-slate-950/80 to-slate-900/90 border border-rose-500/20 rounded-2xl p-4 text-center relative overflow-hidden">
                        <div className="text-[11px] uppercase tracking-wider text-rose-400 font-semibold mb-1 flex items-center justify-center gap-1.5">
                            <span className="w-1.5 h-1.5 rounded-full bg-rose-500 animate-ping" />
                            Pratinjau Kartu (Live Preview)
                        </div>
                        <div className="my-2">
                            <div className="font-chinese text-4xl sm:text-5xl font-bold text-white min-h-[50px] flex items-center justify-center">
                                {data.hanzi || <span className="text-slate-600">汉字</span>}
                            </div>
                            <div className="text-rose-400 font-medium tracking-wide mt-1 text-base min-h-[24px]">
                                {data.pinyin || <span className="text-slate-600">pīnyīn</span>}
                            </div>
                            {(data.dibaca || data.pinyin) && (
                                <div className="mt-1.5 inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full bg-slate-100/80 dark:bg-slate-950/80 border border-slate-200 dark:border-slate-800 text-xs font-mono text-amber-300">
                                    <span className="text-slate-400 dark:text-slate-500 font-sans text-[10px] uppercase font-semibold">baca:</span>
                                    <span className="font-bold tracking-wide">[ {data.dibaca?.trim() || pinyinToIndonesianReading(data.pinyin)} ]</span>
                                </div>
                            )}
                            <div className="text-slate-800 dark:text-slate-200 font-medium text-sm mt-2 min-h-[20px]">
                                {data.meaning || <span className="text-slate-600">Arti kata...</span>}
                            </div>
                        </div>
                        {data.hanzi && (
                            <button
                                type="button"
                                onClick={playPreviewAudio}
                                className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-rose-500/20 text-rose-300 hover:bg-rose-500/30 text-xs font-medium border border-rose-500/30 transition-all mt-1"
                            >
                                <Volume2 className="w-3.5 h-3.5" />
                                Tes Suara Pelafalan
                            </button>
                        )}
                    </div>

                    {/* Hanzi Input */}
                    <div>
                        <div className="flex items-center justify-between mb-1.5">
                            <label htmlFor="hanzi-input" className="block text-sm font-semibold text-slate-200">
                                Karakter Hanzi (汉字) <span className="text-rose-500">*</span>
                            </label>
                            <span className="text-xs text-slate-500">Karakter Mandarin</span>
                        </div>
                        <input
                            id="hanzi-input"
                            type="text"
                            value={data.hanzi}
                            onChange={(e) => setData('hanzi', e.target.value)}
                            onKeyDown={handleKeyDown}
                            placeholder="Contoh: 你好 atau 学习"
                            className="w-full px-4 py-3 bg-slate-100 dark:bg-slate-950 border border-slate-300/80 dark:border-slate-700/80 rounded-xl text-white font-chinese text-xl placeholder:text-slate-600 placeholder:font-sans focus:outline-none focus:ring-2 focus:ring-rose-500/50 focus:border-rose-500 transition-all"
                            autoComplete="off"
                            required
                        />
                        {errors.hanzi && (
                            <p className="mt-1 text-xs text-rose-400">{errors.hanzi}</p>
                        )}
                    </div>

                    {/* Pinyin Input & Helper */}
                    <div>
                        <div className="flex items-center justify-between mb-1.5">
                            <label htmlFor="pinyin-input" className="block text-sm font-semibold text-slate-200">
                                Pinyin (拼音) <span className="text-rose-500">*</span>
                            </label>
                            <span className="text-xs text-slate-500">Gunakan toolbar nada di bawah</span>
                        </div>
                        <input
                            id="pinyin-input"
                            ref={pinyinInputRef}
                            type="text"
                            value={data.pinyin}
                            onChange={(e) => handlePinyinChange(e.target.value)}
                            placeholder="Contoh: nǐ hǎo atau xué xí"
                            className="w-full px-4 py-3 bg-slate-100 dark:bg-slate-950 border border-slate-300/80 dark:border-slate-700/80 rounded-xl text-white font-medium placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-rose-500/50 focus:border-rose-500 transition-all mb-2"
                            autoComplete="off"
                            required
                        />
                        {errors.pinyin && (
                            <p className="mt-1 text-xs text-rose-400 mb-2">{errors.pinyin}</p>
                        )}

                        <PinyinHelper onInsert={handleInsertPinyinTone} />
                    </div>

                    {/* Dibaca (Cara Baca Latin Indonesia) Input */}
                    <div>
                        <div className="flex items-center justify-between mb-1.5">
                            <label htmlFor="dibaca-input" className="block text-sm font-semibold text-slate-200">
                                Cara Baca Latin / Dibaca <span className="text-xs font-normal text-slate-400">(Lidah Indonesia)</span>
                            </label>
                            {data.pinyin && (
                                <button
                                    type="button"
                                    onClick={handleAutoGenerateDibaca}
                                    className="text-xs text-amber-400 hover:text-amber-300 font-medium transition-colors inline-flex items-center gap-1"
                                    title="Isi otomatis ejaan bacaan latin berdasarkan Pinyin"
                                >
                                    <Sparkles className="w-3 h-3" />
                                    Otomatis dari Pinyin
                                </button>
                            )}
                        </div>
                        <input
                            id="dibaca-input"
                            type="text"
                            value={data.dibaca}
                            onChange={(e) => setData('dibaca', e.target.value)}
                            placeholder="Contoh: pa pa (bàba), phing kwo (píngguǒ), kwo (guǒ)"
                            className="w-full px-4 py-3 bg-slate-100 dark:bg-slate-950 border border-slate-300/80 dark:border-slate-700/80 rounded-xl text-amber-300 font-mono text-sm placeholder:text-slate-600 placeholder:font-sans focus:outline-none focus:ring-2 focus:ring-amber-500/40 focus:border-amber-500/60 transition-all"
                            autoComplete="off"
                        />
                        <div className="mt-1 flex items-center justify-between text-[11px] text-slate-500">
                            <span>Bantuan ejaan bunyi untuk penutur Indonesia (misal p dibaca ph, b dibaca p, g dibaca k, d dibaca t)</span>
                            {errors.dibaca && (
                                <span className="text-rose-400">{errors.dibaca}</span>
                            )}
                        </div>
                    </div>

                    {/* Meaning Input */}
                    <div>
                        <label htmlFor="meaning-input" className="block text-sm font-semibold text-slate-800 dark:text-slate-200 mb-1.5">
                            Arti / Makna <span className="text-rose-500">*</span>
                        </label>
                        <textarea
                            id="meaning-input"
                            rows={2}
                            value={data.meaning}
                            onChange={(e) => setData('meaning', e.target.value)}
                            placeholder="Contoh: Halo / Apa kabar"
                            className="w-full px-4 py-3 bg-slate-100 dark:bg-slate-950 border border-slate-300/80 dark:border-slate-700/80 rounded-xl text-white placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-rose-500/50 focus:border-rose-500 transition-all resize-none"
                            required
                        />
                        {errors.meaning && (
                            <p className="mt-1 text-xs text-rose-400">{errors.meaning}</p>
                        )}
                    </div>

                    {/* Optional Notes */}
                    <div>
                        <label htmlFor="notes-input" className="block text-sm font-semibold text-slate-800 dark:text-slate-200 mb-1.5">
                            Catatan Tambahan <span className="text-xs font-normal text-slate-500">(Opsional / Contoh Kalimat)</span>
                        </label>
                        <textarea
                            id="notes-input"
                            rows={2}
                            value={data.notes}
                            onChange={(e) => setData('notes', e.target.value)}
                            placeholder="Contoh kalimat: 我在学习汉语 (Saya sedang belajar bahasa Mandarin)"
                            className="w-full px-4 py-3 bg-slate-100 dark:bg-slate-950 border border-slate-300/80 dark:border-slate-700/80 rounded-xl text-white placeholder:text-slate-600 focus:outline-none focus:ring-2 focus:ring-rose-500/50 focus:border-rose-500 transition-all resize-none text-sm"
                        />
                        {errors.notes && (
                            <p className="mt-1 text-xs text-rose-400">{errors.notes}</p>
                        )}
                    </div>

                    {/* Actions */}
                    <div className="flex items-center justify-end gap-3 pt-3 border-t border-slate-800">
                        <button
                            type="button"
                            onClick={onClose}
                            className="px-5 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:text-white hover:bg-slate-100 dark:bg-slate-800 font-medium text-sm transition-colors"
                        >
                            Batal
                        </button>
                        <button
                            type="submit"
                            disabled={processing}
                            className="flex items-center gap-2 px-6 py-2.5 rounded-xl bg-gradient-to-r from-rose-600 to-rose-500 hover:from-rose-500 hover:to-rose-600 text-white font-semibold text-sm shadow-lg shadow-rose-600/30 hover:shadow-rose-600/50 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                            <Save className="w-4 h-4" />
                            {processing ? 'Menyimpan...' : isEdit ? 'Simpan Perubahan' : 'Simpan Kosakata'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    );
}
